version: "3"

volumes:
  node_modules:

services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: rick-and-morty-development
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
